// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oratoria.Persistence;

#nullable disable

namespace Oratoria.Persistence.Migrations.Settings
{
    [DbContext(typeof(SettingDBContext))]
    partial class SettingDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Oratoria.Persistence.Entities.DeviceSettingEntity", b =>
                {
                    b.Property<string>("DeviceKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Max")
                        .HasColumnType("TEXT");

                    b.Property<string>("Min")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceKey", "Name");

                    b.ToTable("DeviceSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
