<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="UI\Signals\**" />
    <EmbeddedResource Remove="UI\Signals\**" />
    <None Remove="UI\Signals\**" />
    <Page Remove="UI\Signals\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="NLog" Version="5.4.0" />
    <PackageReference Include="NLog.Config" Version="4.7.15" />
    <PackageReference Include="NLog.Schema" Version="5.4.0" />
    <PackageReference Include="NModbus4" Version="2.1.0" />
    <PackageReference Include="System.IO.Ports" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Unilogic\" />
  </ItemGroup>

</Project>
