// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oratoria.Persistence;

#nullable disable

namespace Oratoria.Persistence.Migrations.Recipes
{
    [DbContext(typeof(RecipeDBContext))]
    partial class RecipeDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Oratoria.Persistence.Entities.RecipeEntity", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipes", t =>
                        {
                            t.HasCheckConstraint("ValidModuleId", "ModuleId > 0 AND ModuleId < 10");
                        });
                });

            modelBuilder.Entity("Oratoria.Persistence.Entities.RecipeParameterEntity", b =>
                {
                    b.Property<Guid>("ParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StepId")
                        .HasColumnType("TEXT");

                    b.HasKey("ParameterId");

                    b.HasIndex("StepId");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("Oratoria.Persistence.Entities.RecipeStepEntity", b =>
                {
                    b.Property<Guid>("StepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.HasKey("StepId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Steps", t =>
                        {
                            t.HasCheckConstraint("ValidNumber", "Number > 0 AND Number < 100");
                        });
                });

            modelBuilder.Entity("Oratoria.Persistence.Entities.RecipeValueEntity", b =>
                {
                    b.Property<Guid>("ValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParameterId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("ValueId");

                    b.HasIndex("ParameterId")
                        .IsUnique();

                    b.ToTable("Values");
                });

            modelBuilder.Entity("Oratoria.Persistence.Entities.RecipeParameterEntity", b =>
                {
                    b.HasOne("Oratoria.Persistence.Entities.RecipeStepEntity", "Step")
                        .WithMany("Parameters")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Step");
                });

            modelBuilder.Entity("Oratoria.Persistence.Entities.RecipeStepEntity", b =>
                {
                    b.HasOne("Oratoria.Persistence.Entities.RecipeEntity", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Oratoria.Persistence.Entities.RecipeValueEntity", b =>
                {
                    b.HasOne("Oratoria.Persistence.Entities.RecipeParameterEntity", null)
                        .WithOne("Value")
                        .HasForeignKey("Oratoria.Persistence.Entities.RecipeValueEntity", "ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Oratoria.Persistence.Entities.RecipeEntity", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Oratoria.Persistence.Entities.RecipeParameterEntity", b =>
                {
                    b.Navigation("Value")
                        .IsRequired();
                });

            modelBuilder.Entity("Oratoria.Persistence.Entities.RecipeStepEntity", b =>
                {
                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
