// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oratoria.Persistence;

#nullable disable

namespace Oratoria.Persistence.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Oratoria.Persistence.Entities.RoleEntity", b =>
                {
                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Role");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Role = 0
                        },
                        new
                        {
                            Role = 1
                        },
                        new
                        {
                            Role = 2
                        },
                        new
                        {
                            Role = 3
                        },
                        new
                        {
                            Role = 4
                        });
                });

            modelBuilder.Entity("Oratoria.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Oratoria.Persistence.Entities.UserEntity", b =>
                {
                    b.HasOne("Oratoria.Persistence.Entities.RoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
